#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${BUILD_DIR:-${SCRIPT_DIR}/build}"
JOBS="${JOBS:-$(nproc)}"
BUILD_TYPE="${BUILD_TYPE:-Release}"
SDK_DIR="${SCRIPT_DIR}/sdk"

SAP_CAMERA_ROOT="${SAP_CAMERA_ROOT:-${SDK_DIR}/sap_camera}"
SAP_COMMON_ROOT="${SAP_COMMON_ROOT:-${SDK_DIR}/sap_common}"

BUILD_ROS2="${BUILD_ROS2:-OFF}"
BUILD_RSCL="${BUILD_RSCL:-ON}"
CONFIG_PLATFORM="${CONFIG_PLATFORM:-x86}"
CONFIG_SUBDIR="${CONFIG_SUBDIR:-config/dlp_node/${CONFIG_PLATFORM}}"
if [[ -z "${BUILD_RSCL_APP:-}" ]]; then
  if [[ -f "${SAP_CAMERA_ROOT}/lib/libsap_camera.so" && \
        -f "${SAP_COMMON_ROOT}/lib/libsap_common.so" ]]; then
    BUILD_RSCL_APP="ON"
  else
    BUILD_RSCL_APP="OFF"
  fi
fi
BUILD_SENSEAUTO_CONVERTERS="${BUILD_SENSEAUTO_CONVERTERS:-ON}"

cmake -S "${SCRIPT_DIR}" -B "${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
  -DSAP_CAMERA_ROOT="${SAP_CAMERA_ROOT}" \
  -DSAP_COMMON_ROOT="${SAP_COMMON_ROOT}" \
  -DUSHARING_DLP_NODE_BUILD_ROS2="${BUILD_ROS2}" \
  -DUSHARING_DLP_NODE_BUILD_RSCL="${BUILD_RSCL}" \
  -DUSHARING_DLP_NODE_BUILD_RSCL_APP="${BUILD_RSCL_APP}" \
  -DUSHARING_DLP_NODE_BUILD_SENSEAUTO_CONVERTERS="${BUILD_SENSEAUTO_CONVERTERS}" \
  -DUSHARING_DLP_NODE_CONFIG_PLATFORM="${CONFIG_PLATFORM}" \
  -DUSHARING_DLP_NODE_DEFAULT_CONFIG_SUBDIR="${CONFIG_SUBDIR}"

cmake --build "${BUILD_DIR}" -j"${JOBS}" -- "$@"
