// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bipartite_graph_solver.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_bipartite_5fgraph_5fsolver_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_bipartite_5fgraph_5fsolver_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_bipartite_5fgraph_5fsolver_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_bipartite_5fgraph_5fsolver_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_bipartite_5fgraph_5fsolver_2eproto;
namespace senseAD {
namespace perception {
class GraphSolverParameter;
class GraphSolverParameterDefaultTypeInternal;
extern GraphSolverParameterDefaultTypeInternal _GraphSolverParameter_default_instance_;
}  // namespace perception
}  // namespace senseAD
PROTOBUF_NAMESPACE_OPEN
template<> ::senseAD::perception::GraphSolverParameter* Arena::CreateMaybeMessage<::senseAD::perception::GraphSolverParameter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace senseAD {
namespace perception {

// ===================================================================

class GraphSolverParameter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:senseAD.perception.GraphSolverParameter) */ {
 public:
  inline GraphSolverParameter() : GraphSolverParameter(nullptr) {}
  virtual ~GraphSolverParameter();

  GraphSolverParameter(const GraphSolverParameter& from);
  GraphSolverParameter(GraphSolverParameter&& from) noexcept
    : GraphSolverParameter() {
    *this = ::std::move(from);
  }

  inline GraphSolverParameter& operator=(const GraphSolverParameter& from) {
    CopyFrom(from);
    return *this;
  }
  inline GraphSolverParameter& operator=(GraphSolverParameter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GraphSolverParameter& default_instance();

  static inline const GraphSolverParameter* internal_default_instance() {
    return reinterpret_cast<const GraphSolverParameter*>(
               &_GraphSolverParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GraphSolverParameter& a, GraphSolverParameter& b) {
    a.Swap(&b);
  }
  inline void Swap(GraphSolverParameter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GraphSolverParameter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GraphSolverParameter* New() const final {
    return CreateMaybeMessage<GraphSolverParameter>(nullptr);
  }

  GraphSolverParameter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GraphSolverParameter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GraphSolverParameter& from);
  void MergeFrom(const GraphSolverParameter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GraphSolverParameter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "senseAD.perception.GraphSolverParameter";
  }
  protected:
  explicit GraphSolverParameter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_bipartite_5fgraph_5fsolver_2eproto);
    return ::descriptor_table_bipartite_5fgraph_5fsolver_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBipartiteGraphSolverTypeFieldNumber = 1,
    kValidThresholdFieldNumber = 3,
    kNeighborMaxDistanceMeterFieldNumber = 5,
    kMatchCapacityFieldNumber = 2,
    kNearestNeighborsNumFieldNumber = 4,
  };
  // required string bipartite_graph_solver_type = 1 [default = "KMBipartiteGraphSolver"];
  bool has_bipartite_graph_solver_type() const;
  private:
  bool _internal_has_bipartite_graph_solver_type() const;
  public:
  void clear_bipartite_graph_solver_type();
  const std::string& bipartite_graph_solver_type() const;
  void set_bipartite_graph_solver_type(const std::string& value);
  void set_bipartite_graph_solver_type(std::string&& value);
  void set_bipartite_graph_solver_type(const char* value);
  void set_bipartite_graph_solver_type(const char* value, size_t size);
  std::string* mutable_bipartite_graph_solver_type();
  std::string* release_bipartite_graph_solver_type();
  void set_allocated_bipartite_graph_solver_type(std::string* bipartite_graph_solver_type);
  private:
  const std::string& _internal_bipartite_graph_solver_type() const;
  void _internal_set_bipartite_graph_solver_type(const std::string& value);
  std::string* _internal_mutable_bipartite_graph_solver_type();
  public:

  // optional float valid_threshold = 3 [default = 0];
  bool has_valid_threshold() const;
  private:
  bool _internal_has_valid_threshold() const;
  public:
  void clear_valid_threshold();
  float valid_threshold() const;
  void set_valid_threshold(float value);
  private:
  float _internal_valid_threshold() const;
  void _internal_set_valid_threshold(float value);
  public:

  // optional float neighbor_max_distance_meter = 5 [default = 0.5];
  bool has_neighbor_max_distance_meter() const;
  private:
  bool _internal_has_neighbor_max_distance_meter() const;
  public:
  void clear_neighbor_max_distance_meter();
  float neighbor_max_distance_meter() const;
  void set_neighbor_max_distance_meter(float value);
  private:
  float _internal_neighbor_max_distance_meter() const;
  void _internal_set_neighbor_max_distance_meter(float value);
  public:

  // optional uint32 match_capacity = 2 [default = 1];
  bool has_match_capacity() const;
  private:
  bool _internal_has_match_capacity() const;
  public:
  void clear_match_capacity();
  ::PROTOBUF_NAMESPACE_ID::uint32 match_capacity() const;
  void set_match_capacity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_match_capacity() const;
  void _internal_set_match_capacity(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 nearest_neighbors_num = 4 [default = 1];
  bool has_nearest_neighbors_num() const;
  private:
  bool _internal_has_nearest_neighbors_num() const;
  public:
  void clear_nearest_neighbors_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 nearest_neighbors_num() const;
  void set_nearest_neighbors_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_nearest_neighbors_num() const;
  void _internal_set_nearest_neighbors_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:senseAD.perception.GraphSolverParameter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  static const ::PROTOBUF_NAMESPACE_ID::internal::LazyString _i_give_permission_to_break_this_code_default_bipartite_graph_solver_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bipartite_graph_solver_type_;
  float valid_threshold_;
  float neighbor_max_distance_meter_;
  ::PROTOBUF_NAMESPACE_ID::uint32 match_capacity_;
  ::PROTOBUF_NAMESPACE_ID::uint32 nearest_neighbors_num_;
  friend struct ::TableStruct_bipartite_5fgraph_5fsolver_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GraphSolverParameter

// required string bipartite_graph_solver_type = 1 [default = "KMBipartiteGraphSolver"];
inline bool GraphSolverParameter::_internal_has_bipartite_graph_solver_type() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GraphSolverParameter::has_bipartite_graph_solver_type() const {
  return _internal_has_bipartite_graph_solver_type();
}
inline void GraphSolverParameter::clear_bipartite_graph_solver_type() {
  bipartite_graph_solver_type_.ClearToDefault(::senseAD::perception::GraphSolverParameter::_i_give_permission_to_break_this_code_default_bipartite_graph_solver_type_, GetArena());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& GraphSolverParameter::bipartite_graph_solver_type() const {
  // @@protoc_insertion_point(field_get:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
  if (bipartite_graph_solver_type_.IsDefault(nullptr)) return _i_give_permission_to_break_this_code_default_bipartite_graph_solver_type_.get();
  return _internal_bipartite_graph_solver_type();
}
inline void GraphSolverParameter::set_bipartite_graph_solver_type(const std::string& value) {
  _internal_set_bipartite_graph_solver_type(value);
  // @@protoc_insertion_point(field_set:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
}
inline std::string* GraphSolverParameter::mutable_bipartite_graph_solver_type() {
  // @@protoc_insertion_point(field_mutable:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
  return _internal_mutable_bipartite_graph_solver_type();
}
inline const std::string& GraphSolverParameter::_internal_bipartite_graph_solver_type() const {
  return bipartite_graph_solver_type_.Get();
}
inline void GraphSolverParameter::_internal_set_bipartite_graph_solver_type(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  bipartite_graph_solver_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, value, GetArena());
}
inline void GraphSolverParameter::set_bipartite_graph_solver_type(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  bipartite_graph_solver_type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
}
inline void GraphSolverParameter::set_bipartite_graph_solver_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  bipartite_graph_solver_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
}
inline void GraphSolverParameter::set_bipartite_graph_solver_type(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  bipartite_graph_solver_type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::NonEmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
}
inline std::string* GraphSolverParameter::_internal_mutable_bipartite_graph_solver_type() {
  _has_bits_[0] |= 0x00000001u;
  return bipartite_graph_solver_type_.Mutable(::senseAD::perception::GraphSolverParameter::_i_give_permission_to_break_this_code_default_bipartite_graph_solver_type_, GetArena());
}
inline std::string* GraphSolverParameter::release_bipartite_graph_solver_type() {
  // @@protoc_insertion_point(field_release:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
  if (!_internal_has_bipartite_graph_solver_type()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return bipartite_graph_solver_type_.ReleaseNonDefault(nullptr, GetArena());
}
inline void GraphSolverParameter::set_allocated_bipartite_graph_solver_type(std::string* bipartite_graph_solver_type) {
  if (bipartite_graph_solver_type != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  bipartite_graph_solver_type_.SetAllocated(nullptr, bipartite_graph_solver_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:senseAD.perception.GraphSolverParameter.bipartite_graph_solver_type)
}

// optional uint32 match_capacity = 2 [default = 1];
inline bool GraphSolverParameter::_internal_has_match_capacity() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool GraphSolverParameter::has_match_capacity() const {
  return _internal_has_match_capacity();
}
inline void GraphSolverParameter::clear_match_capacity() {
  match_capacity_ = 1u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GraphSolverParameter::_internal_match_capacity() const {
  return match_capacity_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GraphSolverParameter::match_capacity() const {
  // @@protoc_insertion_point(field_get:senseAD.perception.GraphSolverParameter.match_capacity)
  return _internal_match_capacity();
}
inline void GraphSolverParameter::_internal_set_match_capacity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  match_capacity_ = value;
}
inline void GraphSolverParameter::set_match_capacity(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_match_capacity(value);
  // @@protoc_insertion_point(field_set:senseAD.perception.GraphSolverParameter.match_capacity)
}

// optional float valid_threshold = 3 [default = 0];
inline bool GraphSolverParameter::_internal_has_valid_threshold() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool GraphSolverParameter::has_valid_threshold() const {
  return _internal_has_valid_threshold();
}
inline void GraphSolverParameter::clear_valid_threshold() {
  valid_threshold_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline float GraphSolverParameter::_internal_valid_threshold() const {
  return valid_threshold_;
}
inline float GraphSolverParameter::valid_threshold() const {
  // @@protoc_insertion_point(field_get:senseAD.perception.GraphSolverParameter.valid_threshold)
  return _internal_valid_threshold();
}
inline void GraphSolverParameter::_internal_set_valid_threshold(float value) {
  _has_bits_[0] |= 0x00000002u;
  valid_threshold_ = value;
}
inline void GraphSolverParameter::set_valid_threshold(float value) {
  _internal_set_valid_threshold(value);
  // @@protoc_insertion_point(field_set:senseAD.perception.GraphSolverParameter.valid_threshold)
}

// optional uint32 nearest_neighbors_num = 4 [default = 1];
inline bool GraphSolverParameter::_internal_has_nearest_neighbors_num() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool GraphSolverParameter::has_nearest_neighbors_num() const {
  return _internal_has_nearest_neighbors_num();
}
inline void GraphSolverParameter::clear_nearest_neighbors_num() {
  nearest_neighbors_num_ = 1u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GraphSolverParameter::_internal_nearest_neighbors_num() const {
  return nearest_neighbors_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GraphSolverParameter::nearest_neighbors_num() const {
  // @@protoc_insertion_point(field_get:senseAD.perception.GraphSolverParameter.nearest_neighbors_num)
  return _internal_nearest_neighbors_num();
}
inline void GraphSolverParameter::_internal_set_nearest_neighbors_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  nearest_neighbors_num_ = value;
}
inline void GraphSolverParameter::set_nearest_neighbors_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_nearest_neighbors_num(value);
  // @@protoc_insertion_point(field_set:senseAD.perception.GraphSolverParameter.nearest_neighbors_num)
}

// optional float neighbor_max_distance_meter = 5 [default = 0.5];
inline bool GraphSolverParameter::_internal_has_neighbor_max_distance_meter() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool GraphSolverParameter::has_neighbor_max_distance_meter() const {
  return _internal_has_neighbor_max_distance_meter();
}
inline void GraphSolverParameter::clear_neighbor_max_distance_meter() {
  neighbor_max_distance_meter_ = 0.5f;
  _has_bits_[0] &= ~0x00000004u;
}
inline float GraphSolverParameter::_internal_neighbor_max_distance_meter() const {
  return neighbor_max_distance_meter_;
}
inline float GraphSolverParameter::neighbor_max_distance_meter() const {
  // @@protoc_insertion_point(field_get:senseAD.perception.GraphSolverParameter.neighbor_max_distance_meter)
  return _internal_neighbor_max_distance_meter();
}
inline void GraphSolverParameter::_internal_set_neighbor_max_distance_meter(float value) {
  _has_bits_[0] |= 0x00000004u;
  neighbor_max_distance_meter_ = value;
}
inline void GraphSolverParameter::set_neighbor_max_distance_meter(float value) {
  _internal_set_neighbor_max_distance_meter(value);
  // @@protoc_insertion_point(field_set:senseAD.perception.GraphSolverParameter.neighbor_max_distance_meter)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace perception
}  // namespace senseAD

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_bipartite_5fgraph_5fsolver_2eproto
